import type { ClientRecord } from "../types";

/** Elena Whitmore — original $300M Greenwich walkthrough household. */
export const elenaClient: ClientRecord = {
  id: "elena-whitmore",
  household: {
    name: "Whitmore Household",
    clientFirstName: "Elena",
    principals: "Elena & Marcus Whitmore",
    domicile: "Greenwich, CT",
    entity: "Whitmore Family Revocable Trust",
    accountValue: 186_400_000,
    investable: 228_000_000,
    additionalInvestable: 41_600_000,
    realEstate: 48_000_000,
    otherHousehold: 24_000_000,
    householdValue: 300_000_000,
    liquidity: 18_200_000,
    risk: {
      label: "Moderate growth",
      horizon: "7-year planning window",
      capacity: "Can absorb a 15–20% drawdown without forced sale",
      privateMarketsSleeve: 0.127,
    },
    dataAsOf: "2026-09-04",
    sourceNote:
      "Holdings and style boxes illustrated as if first provided by Morningstar and Informa. Not live manager feeds.",
  },
  advisor: {
    name: "Linda McDonald",
    title: "Managing Director, Private Client",
    firm: "McDonald Advisory Group",
    brokerCheckId: "111111",
    crdFirm: "CRD 888888 (illustrative)",
    verified: true,
    since: "2019-03-12",
  },
  accounts: [
    {
      id: "ml-pw",
      name: "Private Wealth brokerage",
      type: "Taxable joint",
      custodian: "Merrill Lynch",
      balance: 84_200_000,
      verifiedCustodian: true,
      sleeve: "taxable",
    },
    {
      id: "fid-tax",
      name: "Taxable brokerage",
      type: "Individual",
      custodian: "Fidelity",
      balance: 31_400_000,
      verifiedCustodian: false,
      sleeve: "taxable",
    },
    {
      id: "schwab-ira",
      name: "Traditional IRA (rollover candidate)",
      type: "IRA",
      custodian: "Charles Schwab",
      balance: 29_100_000,
      verifiedCustodian: false,
      sleeve: "qualified",
    },
    {
      id: "oak-pe",
      name: "PE feeder / secondaries sleeve",
      type: "Private fund interest",
      custodian: "Oakridge Partners (admin)",
      balance: 21_800_000,
      verifiedCustodian: false,
      sleeve: "private",
    },
    {
      id: "cash",
      name: "Treasury & municipal reserve",
      type: "Cash / short duration",
      custodian: "First Atlantic Private Bank",
      balance: 19_900_000,
      verifiedCustodian: false,
      sleeve: "cash",
    },
  ],
  holdings: [
    { id: "ml-aapl", accountId: "ml-pw", assetClass: "equity", ticker: "AAPL", name: "Apple Inc.", kind: "Common stock", value: 12_400_000 },
    { id: "ml-msft", accountId: "ml-pw", assetClass: "equity", ticker: "MSFT", name: "Microsoft Corp.", kind: "Common stock", value: 11_800_000 },
    { id: "ml-nvda", accountId: "ml-pw", assetClass: "equity", ticker: "NVDA", name: "NVIDIA Corp.", kind: "Common stock", value: 9_600_000 },
    { id: "ml-amzn", accountId: "ml-pw", assetClass: "equity", ticker: "AMZN", name: "Amazon.com Inc.", kind: "Common stock", value: 8_200_000 },
    { id: "ml-googl", accountId: "ml-pw", assetClass: "equity", ticker: "GOOGL", name: "Alphabet Inc. Class A", kind: "Common stock", value: 7_100_000 },
    { id: "ml-voo", accountId: "ml-pw", assetClass: "equity", ticker: "VOO", name: "Vanguard S&P 500 ETF", kind: "ETF", value: 10_200_000 },
    { id: "ml-ctmuni", accountId: "ml-pw", assetClass: "fixed-income", ticker: "CT GO", name: "Connecticut GO 5.00% 2034", kind: "Municipal bond", value: 8_200_000 },
    { id: "ml-munisma", accountId: "ml-pw", assetClass: "fixed-income", ticker: "MUNI SMA", name: "National + CT municipal SMA", kind: "SMA sleeve", value: 6_100_000 },
    { id: "ml-lqd", accountId: "ml-pw", assetClass: "fixed-income", ticker: "LQD", name: "Investment-grade corporate sleeve", kind: "ETF sleeve", value: 3_400_000 },
    { id: "ml-vnq", accountId: "ml-pw", assetClass: "real-assets", ticker: "VNQ", name: "Vanguard Real Estate ETF", kind: "ETF", value: 2_800_000 },
    { id: "ml-gld", accountId: "ml-pw", assetClass: "real-assets", ticker: "GLD", name: "SPDR Gold Shares", kind: "ETF", value: 2_100_000 },
    { id: "ml-peov", accountId: "ml-pw", assetClass: "private", ticker: "PE-CO", name: "PE co-invest overlay", kind: "Private interest", value: 1_800_000 },
    { id: "ml-sweep", accountId: "ml-pw", assetClass: "cash", ticker: "SWEEP", name: "Merrill cash sweep", kind: "Cash", value: 500_000 },
    { id: "fid-brkb", accountId: "fid-tax", assetClass: "equity", ticker: "BRK.B", name: "Berkshire Hathaway Class B", kind: "Common stock", value: 6_400_000 },
    { id: "fid-vti", accountId: "fid-tax", assetClass: "equity", ticker: "VTI", name: "Vanguard Total Stock Market", kind: "ETF", value: 5_100_000 },
    { id: "fid-vxus", accountId: "fid-tax", assetClass: "equity", ticker: "VXUS", name: "Vanguard Total International", kind: "ETF", value: 3_200_000 },
    { id: "fid-mub", accountId: "fid-tax", assetClass: "fixed-income", ticker: "MUB", name: "iShares National Muni Bond", kind: "ETF", value: 5_100_000 },
    { id: "fid-tlt", accountId: "fid-tax", assetClass: "fixed-income", ticker: "TLT", name: "iShares 20+ Year Treasury", kind: "ETF", value: 3_800_000 },
    { id: "fid-lqd", accountId: "fid-tax", assetClass: "fixed-income", ticker: "LQD", name: "iShares iBoxx IG Corporate", kind: "ETF", value: 3_200_000 },
    { id: "fid-iau", accountId: "fid-tax", assetClass: "real-assets", ticker: "IAU", name: "iShares Gold Trust", kind: "ETF", value: 1_600_000 },
    { id: "fid-vnqi", accountId: "fid-tax", assetClass: "real-assets", ticker: "VNQI", name: "Vanguard Global ex-US REIT", kind: "ETF", value: 1_200_000 },
    { id: "fid-spaxx", accountId: "fid-tax", assetClass: "cash", ticker: "SPAXX", name: "Fidelity Government Money Market", kind: "Money market", value: 1_800_000 },
    { id: "sch-swtsx", accountId: "schwab-ira", assetClass: "equity", ticker: "SWTSX", name: "Schwab Total Stock Market Index", kind: "Mutual fund", value: 8_400_000 },
    { id: "sch-swisx", accountId: "schwab-ira", assetClass: "equity", ticker: "SWISX", name: "Schwab International Index", kind: "Mutual fund", value: 3_200_000 },
    { id: "sch-swagx", accountId: "schwab-ira", assetClass: "fixed-income", ticker: "SWAGX", name: "Schwab US Aggregate Bond", kind: "Mutual fund", value: 7_200_000 },
    { id: "sch-vwitx", accountId: "schwab-ira", assetClass: "fixed-income", ticker: "VWITX", name: "Vanguard Intermediate-Term Tax-Exempt", kind: "Mutual fund", value: 3_400_000 },
    { id: "sch-vgslx", accountId: "schwab-ira", assetClass: "real-assets", ticker: "VGSLX", name: "Vanguard Real Estate Index", kind: "Mutual fund", value: 4_200_000 },
    { id: "sch-swvxx", accountId: "schwab-ira", assetClass: "cash", ticker: "SWVXX", name: "Schwab Government Money", kind: "Money market", value: 2_700_000 },
    { id: "oak-feeder", accountId: "oak-pe", assetClass: "private", ticker: "OAK-III", name: "Oakridge PE Feeder III", kind: "Private fund", value: 12_400_000 },
    { id: "oak-sec", accountId: "oak-pe", assetClass: "private", ticker: "OAK-S24", name: "Oakridge Secondaries 2024", kind: "Private fund", value: 6_200_000 },
    { id: "oak-spv", accountId: "oak-pe", assetClass: "private", ticker: "OAK-SPV", name: "Co-invest SPV (illustrated)", kind: "SPV interest", value: 3_200_000 },
    { id: "fa-tbill", accountId: "cash", assetClass: "cash", ticker: "T-BILL", name: "US Treasury bills 0–12m", kind: "Treasury", value: 8_200_000 },
    { id: "fa-op", accountId: "cash", assetClass: "cash", ticker: "CASH", name: "First Atlantic operating cash", kind: "Cash", value: 3_200_000 },
    { id: "fa-muni", accountId: "cash", assetClass: "fixed-income", ticker: "CT ST", name: "CT short municipal reserve", kind: "Municipal bond", value: 8_500_000 },
  ],
  consent: {
    shared: true,
    lastChanged: "2026-08-12",
    scopes: ["Holdings and sleeves", "Risk posture and liquidity", "Verification badges", "Domicile"],
  },
  attestations: [
    {
      date: "2026-09-01",
      kind: "custodian",
      title: "Merrill Lynch custodian match",
      detail:
        "Account ending 4481 illustrated as custodian-verified. Badge is mock data stored on the client record — no DTCC or firm API was called.",
    },
    {
      date: "2026-08-20",
      kind: "advisor",
      title: "Linda McDonald · BrokerCheck 111111",
      detail:
        "Advisor identity illustrated as FINRA BrokerCheck–style verification. ID 111111 is a placeholder, not a live CRD lookup.",
    },
    {
      date: "2026-08-02",
      kind: "document",
      title: "Accredited / QP letter reused",
      detail:
        "Ops packet reuses the household’s illustrated investor letter. Document is a fixture on this client record, not a signed original.",
    },
  ],
  opsPacket: {
    title: "IRA rollover enrollment packet",
    from: "Charles Schwab Traditional IRA",
    to: "First Atlantic Qualified Rollover IRA",
    reused: 14,
    total: 18,
    fields: [
      { label: "Household legal name", value: "Elena Whitmore & Marcus Whitmore", source: "Passport", reused: true },
      { label: "Legal entity", value: "Whitmore Family Revocable Trust", source: "Passport", reused: true },
      { label: "Domicile", value: "Greenwich, CT", source: "Passport", reused: true },
      { label: "Advisor of record", value: "Linda McDonald · BrokerCheck 111111", source: "Verification", reused: true },
      { label: "Delivering account", value: "Schwab IRA · •••• 9021", source: "Passport", reused: true },
      { label: "Receiving account", value: "First Atlantic QRP · pending", source: "Ops clerk", reused: false },
      { label: "Cost basis method", value: "Specific ID (illustrated)", source: "Passport", reused: true },
      { label: "Beneficiaries", value: "Primary: spouse · Contingent: Whitmore 2008 GST", source: "Passport", reused: true },
      { label: "W-9 / TIN attestation", value: "On file · last4 4418", source: "Reusable docs", reused: true },
      { label: "ACH instructions", value: "First Atlantic operating · •••• 2209", source: "Reusable docs", reused: true },
      { label: "Risk questionnaire", value: "Moderate growth · 2026-04 refresh", source: "Passport", reused: true },
      { label: "Accredited investor letter", value: "Illustrated QP letter · 2026-01", source: "Reusable docs", reused: true },
      { label: "Passport share consent", value: "On · any paying institution may offer", source: "Consent", reused: true },
      { label: "Morningstar-style holdings extract", value: "Taxable + IRA sleeves (fixture)", source: "Illustrated feed", reused: true },
      { label: "Informa-style product mapping", value: "Muni SMA + SBL eligibility (fixture)", source: "Illustrated feed", reused: true },
      { label: "Medallion / wet signature", value: "Required at funding", source: "Still needed", reused: false },
      { label: "Receiving plan acceptance", value: "Institution ops queue", source: "Still needed", reused: false },
      { label: "State rollover notice", value: "CT notice to be generated", source: "Still needed", reused: false },
    ],
  },
  verifiedCustodian: {
    badge: "Merrill Lynch",
    accountMask: "Account ending 4481",
    title: "Private Wealth brokerage",
    body: "The taxable joint account is illustrated as custodian-matched to Merrill Lynch. Other sleeves (Fidelity, Schwab, Oakridge admin, First Atlantic cash) remain unverified in this walkthrough so the badge is meaningful.",
  },
};
