import { generateClient, type HouseholdSpec } from "./generator.ts";
import type { ClientRecord } from "../types.ts";

/**
 * The wider book of households behind Elena and Priya — segments range from
 * conservative retirees to international UHNW so institution matching, AUM,
 * and placement revenue have real variety to work with.
 */
const HOUSEHOLD_SPECS: HouseholdSpec[] = [
  {
    id: "chen-family",
    name: "Chen Household",
    clientFirstName: "Daniel",
    principals: "Daniel & Mei Chen",
    domicile: "San Francisco, CA",
    entity: "Chen Family Revocable Trust",
    accounts: [
      { id: "ms-pw", name: "Private Wealth brokerage", type: "Taxable joint", custodian: "Morgan Stanley", balance: 28_000_000, verifiedCustodian: true, sleeve: "taxable" },
      { id: "schwab-ira", name: "Traditional IRA", type: "IRA", custodian: "Charles Schwab", balance: 6_500_000, sleeve: "qualified" },
      { id: "jpm-cash", name: "Treasury & operating cash", type: "Cash / short duration", custodian: "J.P. Morgan Private Bank", balance: 4_000_000, sleeve: "cash" },
    ],
    additionalInvestable: 3_000_000,
    realEstate: 6_500_000,
    otherHousehold: 2_000_000,
    liquidity: 5_500_000,
    risk: {
      label: "Growth",
      horizon: "8-year planning window",
      capacity: "Can absorb a 20% drawdown without forced sale",
      privateMarketsSleeve: 0,
    },
    dataAsOf: "2026-09-08",
    advisor: {
      name: "Rachel Kim",
      title: "Senior Vice President, Private Client",
      firm: "Kim Wealth Partners",
      brokerCheckId: "333333",
      crdFirm: "CRD 555555",
      verified: true,
      since: "2017-05-02",
    },
    verifiedAccountMask: "Account ending 3381",
    ops: {
      title: "IRA rollover enrollment packet",
      from: "Charles Schwab Traditional IRA",
      to: "Morgan Stanley Rollover IRA",
      deliveringAccount: "Schwab IRA · •••• 6641",
      receivingAccount: "Morgan Stanley Rollover IRA · pending",
      stateNotice: "CA notice to be generated",
    },
    consentLastChanged: "2026-08-21",
  },
  {
    id: "delgado-family",
    name: "Delgado Household",
    clientFirstName: "Robert",
    principals: "Robert & Anne Delgado",
    domicile: "Austin, TX",
    entity: "Delgado Living Trust",
    accounts: [
      { id: "fid-tax", name: "Taxable brokerage", type: "Individual", custodian: "Fidelity", balance: 9_200_000, verifiedCustodian: true, sleeve: "taxable" },
      { id: "fid-ira", name: "Traditional IRA (rollover candidate)", type: "IRA", custodian: "Fidelity", balance: 6_800_000, sleeve: "qualified" },
      { id: "schwab-cash", name: "Treasury reserve", type: "Cash / short duration", custodian: "Charles Schwab", balance: 2_000_000, sleeve: "cash" },
    ],
    additionalInvestable: 500_000,
    realEstate: 2_400_000,
    otherHousehold: 600_000,
    liquidity: 2_200_000,
    risk: {
      label: "Conservative income",
      horizon: "5-year income window",
      capacity: "Cannot tolerate drawdowns beyond 8%",
      privateMarketsSleeve: 0,
    },
    dataAsOf: "2026-09-11",
    advisor: {
      name: "Tom Barrett",
      title: "Managing Director",
      firm: "Barrett Retirement Advisors",
      brokerCheckId: "444444",
      crdFirm: "CRD 666666",
      verified: true,
      since: "2015-09-14",
    },
    verifiedAccountMask: "Account ending 5520",
    ops: {
      title: "IRA rollover enrollment packet",
      from: "Fidelity Traditional IRA",
      to: "Charles Schwab Rollover IRA",
      deliveringAccount: "Fidelity IRA · •••• 2210",
      receivingAccount: "Schwab Rollover IRA · pending",
      stateNotice: "TX notice to be generated",
    },
    consentLastChanged: "2026-07-30",
  },
  {
    id: "okafor-trust",
    name: "Okafor Family Trust",
    clientFirstName: "Adaeze",
    principals: "Adaeze & Chidi Okafor",
    domicile: "New York, NY",
    entity: "Okafor Family Trust",
    accounts: [
      { id: "bny-custody", name: "Private custody account", type: "Taxable trust", custodian: "BNY Mellon", balance: 62_000_000, verifiedCustodian: true, sleeve: "taxable" },
      { id: "gs-pma", name: "Private wealth account", type: "Taxable joint", custodian: "Goldman Sachs", balance: 25_000_000, sleeve: "taxable" },
      { id: "pe-feeder", name: "PE feeder / secondaries sleeve", type: "Private fund interest", custodian: "Apollo (admin)", balance: 18_000_000, sleeve: "private" },
      { id: "bny-cash", name: "Treasury reserve", type: "Cash / short duration", custodian: "BNY Mellon", balance: 8_000_000, sleeve: "cash" },
    ],
    additionalInvestable: 7_000_000,
    realEstate: 14_000_000,
    otherHousehold: 6_000_000,
    liquidity: 11_000_000,
    risk: {
      label: "Moderate growth",
      horizon: "10-year planning window",
      capacity: "Can absorb a 15% drawdown without forced sale",
      privateMarketsSleeve: 0.16,
    },
    dataAsOf: "2026-09-05",
    advisor: {
      name: "Sofia Marchetti",
      title: "Partner",
      firm: "Marchetti Private Capital",
      brokerCheckId: "555555",
      crdFirm: "CRD 999999",
      verified: true,
      since: "2013-02-20",
    },
    verifiedAccountMask: "Account ending 8804",
    ops: {
      title: "Trust account transfer packet",
      from: "Goldman Sachs private wealth",
      to: "BNY Mellon trust custody",
      deliveringAccount: "Goldman PMA · •••• 3390",
      receivingAccount: "BNY trust custody · pending",
      stateNotice: "NY notice to be generated",
    },
    consentLastChanged: "2026-08-02",
  },
  {
    id: "lindqvist-estate",
    name: "Lindqvist Household",
    clientFirstName: "Hannah",
    principals: "Hannah Lindqvist",
    domicile: "Chicago, IL",
    entity: "Lindqvist Inheritance Trust",
    accounts: [
      { id: "nt-inherited", name: "Inherited brokerage", type: "Individual", custodian: "Northern Trust", balance: 7_100_000, verifiedCustodian: true, sleeve: "taxable" },
      { id: "nt-cash", name: "Treasury reserve", type: "Cash / short duration", custodian: "Northern Trust", balance: 1_900_000, sleeve: "cash" },
    ],
    additionalInvestable: 500_000,
    realEstate: 1_800_000,
    otherHousehold: 700_000,
    liquidity: 1_900_000,
    risk: {
      label: "Capital preservation",
      horizon: "Indefinite horizon",
      capacity: "Minimal drawdown tolerance",
      privateMarketsSleeve: 0,
    },
    dataAsOf: "2026-09-09",
    advisor: {
      name: "James Whitfield",
      title: "Senior Trust Officer",
      firm: "Whitfield Fiduciary Group",
      brokerCheckId: "666666",
      crdFirm: "CRD 101010",
      verified: true,
      since: "2020-11-30",
    },
    verifiedAccountMask: "Account ending 1147",
    ops: {
      title: "Estate account transfer packet",
      from: "Northern Trust estate account",
      to: "Northern Trust individual account",
      deliveringAccount: "Northern Trust estate · •••• 7783",
      receivingAccount: "Northern Trust individual · pending",
      stateNotice: "IL notice to be generated",
    },
    consentLastChanged: "2026-08-25",
  },
  {
    id: "nakamura-family",
    name: "Nakamura Household",
    clientFirstName: "Kenji",
    principals: "Kenji & Aiko Nakamura",
    domicile: "Honolulu, HI",
    entity: "Nakamura Family Revocable Trust",
    accounts: [
      { id: "ubs-pw", name: "Private wealth account", type: "Taxable joint", custodian: "UBS", balance: 34_000_000, verifiedCustodian: true, sleeve: "taxable" },
      { id: "fid-401k", name: "Former-employer 401(k) (rollover candidate)", type: "401(k)", custodian: "Fidelity", balance: 9_000_000, sleeve: "qualified" },
      { id: "ubs-cash", name: "Treasury & operating cash", type: "Cash / short duration", custodian: "UBS", balance: 6_000_000, sleeve: "cash" },
    ],
    additionalInvestable: 4_000_000,
    realEstate: 9_000_000,
    otherHousehold: 3_000_000,
    liquidity: 7_500_000,
    risk: {
      label: "Growth",
      horizon: "12-year planning window",
      capacity: "Can absorb a 20% drawdown without forced sale",
      privateMarketsSleeve: 0,
    },
    dataAsOf: "2026-09-07",
    advisor: {
      name: "Grace Huang",
      title: "Managing Director, International",
      firm: "Huang Global Wealth",
      brokerCheckId: "777777",
      crdFirm: "CRD 202020",
      verified: true,
      since: "2016-07-19",
    },
    verifiedAccountMask: "Account ending 2290",
    ops: {
      title: "401(k) rollover enrollment packet",
      from: "Fidelity former-employer 401(k)",
      to: "UBS Rollover IRA",
      deliveringAccount: "Fidelity 401(k) · •••• 8841",
      receivingAccount: "UBS Rollover IRA · pending",
      stateNotice: "HI notice to be generated",
    },
    consentLastChanged: "2026-08-16",
  },
  {
    id: "beaumont-family",
    name: "Beaumont Household",
    clientFirstName: "William",
    principals: "William & Clara Beaumont",
    domicile: "Boston, MA",
    entity: "Beaumont Family Trust",
    accounts: [
      { id: "stst-custody", name: "Private custody account", type: "Taxable trust", custodian: "State Street Private", balance: 95_000_000, verifiedCustodian: true, sleeve: "taxable" },
      { id: "bny-ira", name: "Traditional IRA", type: "IRA", custodian: "BNY Mellon", balance: 22_000_000, sleeve: "qualified" },
      { id: "pe-sleeve", name: "PE feeder / secondaries sleeve", type: "Private fund interest", custodian: "HarbourVest (admin)", balance: 30_000_000, sleeve: "private" },
      { id: "stst-cash", name: "Treasury reserve", type: "Cash / short duration", custodian: "State Street Private", balance: 12_000_000, sleeve: "cash" },
    ],
    additionalInvestable: 11_000_000,
    realEstate: 26_000_000,
    otherHousehold: 14_000_000,
    liquidity: 16_000_000,
    risk: {
      label: "Moderate",
      horizon: "15-year horizon",
      capacity: "Can absorb a 15–20% drawdown without forced sale",
      privateMarketsSleeve: 0.18,
    },
    dataAsOf: "2026-09-03",
    advisor: {
      name: "Charles Pemberton",
      title: "Partner",
      firm: "Pemberton & Sloane",
      brokerCheckId: "888888",
      crdFirm: "CRD 303030",
      verified: true,
      since: "2011-04-05",
    },
    verifiedAccountMask: "Account ending 6623",
    ops: {
      title: "IRA rollover enrollment packet",
      from: "BNY Mellon Traditional IRA",
      to: "State Street Rollover IRA",
      deliveringAccount: "BNY IRA · •••• 1174",
      receivingAccount: "State Street Rollover IRA · pending",
      stateNotice: "MA notice to be generated",
    },
    consentLastChanged: "2026-07-19",
  },
  {
    id: "fernandez-family",
    name: "Fernandez Household",
    clientFirstName: "Diego",
    principals: "Diego & Lucia Fernandez",
    domicile: "Miami, FL",
    entity: "Fernandez Family LLC",
    accounts: [
      { id: "jpm-pw", name: "Private wealth account", type: "Taxable joint", custodian: "J.P. Morgan Private Bank", balance: 20_000_000, verifiedCustodian: true, sleeve: "taxable" },
      { id: "schwab-sep", name: "SEP-IRA", type: "IRA", custodian: "Charles Schwab", balance: 7_000_000, sleeve: "qualified" },
      { id: "biz-equity", name: "Business equity sleeve", type: "Private fund interest", custodian: "Carta (admin)", balance: 4_000_000, sleeve: "private" },
      { id: "jpm-cash", name: "Operating cash", type: "Cash / short duration", custodian: "J.P. Morgan Private Bank", balance: 5_000_000, sleeve: "cash" },
    ],
    additionalInvestable: 6_000_000,
    realEstate: 5_500_000,
    otherHousehold: 2_500_000,
    liquidity: 8_500_000,
    risk: {
      label: "Aggressive growth",
      horizon: "10-year liquidity window",
      capacity: "Can absorb a 25% drawdown without forced sale",
      privateMarketsSleeve: 0.11,
    },
    dataAsOf: "2026-09-12",
    advisor: {
      name: "Isabel Duarte",
      title: "Senior Private Banker",
      firm: "Duarte Wealth Management",
      brokerCheckId: "999999",
      crdFirm: "CRD 404040",
      verified: true,
      since: "2019-08-22",
    },
    verifiedAccountMask: "Account ending 9912",
    ops: {
      title: "SEP-IRA rollover packet",
      from: "Charles Schwab SEP-IRA",
      to: "J.P. Morgan Rollover IRA",
      deliveringAccount: "Schwab SEP · •••• 4456",
      receivingAccount: "J.P. Morgan Rollover IRA · pending",
      stateNotice: "FL notice to be generated",
    },
    consentLastChanged: "2026-09-01",
  },
  {
    id: "ashworth-family",
    name: "Ashworth Household",
    clientFirstName: "Edmund",
    principals: "Edmund & Sophie Ashworth",
    domicile: "London, UK",
    entity: "Ashworth Family Settlement",
    accounts: [
      { id: "ubs-disc", name: "Discretionary portfolio", type: "Taxable joint", custodian: "UBS", balance: 48_000_000, verifiedCustodian: true, sleeve: "taxable" },
      { id: "pe-feeder", name: "PE feeder sleeve", type: "Private fund interest", custodian: "Schroders (admin)", balance: 12_000_000, sleeve: "private" },
      { id: "ubs-cash", name: "Treasury & operating cash", type: "Cash / short duration", custodian: "UBS", balance: 9_000_000, sleeve: "cash" },
    ],
    additionalInvestable: 5_000_000,
    realEstate: 11_000_000,
    otherHousehold: 4_000_000,
    liquidity: 12_000_000,
    risk: {
      label: "Moderate growth",
      horizon: "10-year horizon",
      capacity: "Can absorb a 15% drawdown without forced sale",
      privateMarketsSleeve: 0.17,
    },
    dataAsOf: "2026-09-06",
    advisor: {
      name: "Oliver Grant",
      title: "Director, Private Clients",
      firm: "Grant Mayfair Advisers",
      brokerCheckId: "121212",
      crdFirm: "CRD 505050",
      verified: true,
      since: "2014-10-11",
    },
    verifiedAccountMask: "Account ending 3308",
    ops: {
      title: "Account transfer packet",
      from: "UBS discretionary portfolio",
      to: "WealthPass custody",
      deliveringAccount: "UBS discretionary · •••• 5567",
      receivingAccount: "WealthPass custody · pending",
      stateNotice: "UK notice to be generated",
    },
    consentLastChanged: "2026-08-28",
  },
];

export const GENERATED_CLIENT_SEEDS: ClientRecord[] = HOUSEHOLD_SPECS.map(generateClient);
