import type { ClientRecord } from "../types";

/** Priya Shah — second client record for the local SQLite mock. */
export const priyaClient: ClientRecord = {
  id: "priya-shah",
  household: {
    name: "Shah Household",
    clientFirstName: "Priya",
    principals: "Priya & Arjun Shah",
    domicile: "Los Angeles, CA",
    entity: "Shah Family Revocable Trust",
    accountValue: 48_000_000,
    investable: 56_000_000,
    additionalInvestable: 8_000_000,
    realEstate: 12_000_000,
    otherHousehold: 4_000_000,
    householdValue: 72_000_000,
    liquidity: 6_400_000,
    risk: {
      label: "Aggressive growth",
      horizon: "10-year liquidity window",
      capacity: "Can absorb a 25% drawdown without forced sale",
      privateMarketsSleeve: 0,
    },
    dataAsOf: "2026-09-10",
    sourceNote:
      "Holdings illustrated as if first provided by Morningstar and Informa. Not live manager feeds. Second client record in the local database.",
  },
  advisor: {
    name: "David Park",
    title: "Partner, Private Wealth",
    firm: "Park & Associates Wealth",
    brokerCheckId: "222222",
    crdFirm: "CRD 777777 (illustrative)",
    verified: true,
    since: "2021-06-08",
  },
  accounts: [
    {
      id: "gs-pw",
      name: "Goldman Private Wealth",
      type: "Taxable joint",
      custodian: "Goldman Sachs",
      balance: 22_400_000,
      verifiedCustodian: true,
      sleeve: "taxable",
    },
    {
      id: "schwab-ind",
      name: "Taxable brokerage",
      type: "Individual",
      custodian: "Charles Schwab",
      balance: 9_800_000,
      verifiedCustodian: false,
      sleeve: "taxable",
    },
    {
      id: "fid-401k",
      name: "Former-employer 401(k) (rollover candidate)",
      type: "401(k)",
      custodian: "Fidelity",
      balance: 11_200_000,
      verifiedCustodian: false,
      sleeve: "qualified",
    },
    {
      id: "jpm-cash",
      name: "Treasury & operating cash",
      type: "Cash / short duration",
      custodian: "J.P. Morgan Private Bank",
      balance: 4_600_000,
      verifiedCustodian: false,
      sleeve: "cash",
    },
  ],
  holdings: [
    { id: "gs-nvda", accountId: "gs-pw", assetClass: "equity", ticker: "NVDA", name: "NVIDIA Corp.", kind: "Common stock", value: 5_200_000 },
    { id: "gs-meta", accountId: "gs-pw", assetClass: "equity", ticker: "META", name: "Meta Platforms Inc.", kind: "Common stock", value: 3_800_000 },
    { id: "gs-aapl", accountId: "gs-pw", assetClass: "equity", ticker: "AAPL", name: "Apple Inc.", kind: "Common stock", value: 3_100_000 },
    { id: "gs-tsla", accountId: "gs-pw", assetClass: "equity", ticker: "TSLA", name: "Tesla Inc.", kind: "Common stock", value: 2_400_000 },
    { id: "gs-qqq", accountId: "gs-pw", assetClass: "equity", ticker: "QQQ", name: "Invesco QQQ Trust", kind: "ETF", value: 3_200_000 },
    { id: "gs-camuni", accountId: "gs-pw", assetClass: "fixed-income", ticker: "CA GO", name: "California GO 4.50% 2036", kind: "Municipal bond", value: 2_400_000 },
    { id: "gs-gld", accountId: "gs-pw", assetClass: "real-assets", ticker: "GLD", name: "SPDR Gold Shares", kind: "ETF", value: 1_100_000 },
    { id: "gs-sweep", accountId: "gs-pw", assetClass: "cash", ticker: "SWEEP", name: "Goldman cash sweep", kind: "Cash", value: 1_200_000 },
    { id: "sch-vti", accountId: "schwab-ind", assetClass: "equity", ticker: "VTI", name: "Vanguard Total Stock Market", kind: "ETF", value: 3_600_000 },
    { id: "sch-vxus", accountId: "schwab-ind", assetClass: "equity", ticker: "VXUS", name: "Vanguard Total International", kind: "ETF", value: 1_800_000 },
    { id: "sch-bnd", accountId: "schwab-ind", assetClass: "fixed-income", ticker: "BND", name: "Vanguard Total Bond Market", kind: "ETF", value: 2_400_000 },
    { id: "sch-schd", accountId: "schwab-ind", assetClass: "equity", ticker: "SCHD", name: "Schwab US Dividend Equity", kind: "ETF", value: 1_200_000 },
    { id: "sch-swvxx", accountId: "schwab-ind", assetClass: "cash", ticker: "SWVXX", name: "Schwab Government Money", kind: "Money market", value: 800_000 },
    { id: "fid-fxaix", accountId: "fid-401k", assetClass: "equity", ticker: "FXAIX", name: "Fidelity 500 Index", kind: "Mutual fund", value: 5_400_000 },
    { id: "fid-fspsx", accountId: "fid-401k", assetClass: "equity", ticker: "FSPSX", name: "Fidelity International Index", kind: "Mutual fund", value: 2_100_000 },
    { id: "fid-fxnax", accountId: "fid-401k", assetClass: "fixed-income", ticker: "FXNAX", name: "Fidelity US Bond Index", kind: "Mutual fund", value: 2_600_000 },
    { id: "fid-spaxx", accountId: "fid-401k", assetClass: "cash", ticker: "SPAXX", name: "Fidelity Government Money Market", kind: "Money market", value: 1_100_000 },
    { id: "jpm-tbill", accountId: "jpm-cash", assetClass: "cash", ticker: "T-BILL", name: "US Treasury bills 0–12m", kind: "Treasury", value: 2_800_000 },
    { id: "jpm-op", accountId: "jpm-cash", assetClass: "cash", ticker: "CASH", name: "J.P. Morgan operating cash", kind: "Cash", value: 1_800_000 },
  ],
  consent: {
    shared: true,
    lastChanged: "2026-09-02",
    scopes: ["Holdings and sleeves", "Risk posture and liquidity", "Verification badges", "Domicile"],
  },
  attestations: [
    {
      date: "2026-09-08",
      kind: "custodian",
      title: "Goldman Sachs custodian match",
      detail:
        "Account ending 7720 illustrated as custodian-verified. Badge is stored on this client record — no prime-broker API was called.",
    },
    {
      date: "2026-08-28",
      kind: "advisor",
      title: "David Park · BrokerCheck 222222",
      detail:
        "Advisor identity illustrated as FINRA BrokerCheck–style verification. ID 222222 is a placeholder, not a live CRD lookup.",
    },
    {
      date: "2026-07-15",
      kind: "document",
      title: "Accredited investor letter reused",
      detail:
        "Ops packet reuses the Shah household’s illustrated accredited-investor letter stored on this client record.",
    },
  ],
  opsPacket: {
    title: "401(k) rollover enrollment packet",
    from: "Fidelity former-employer 401(k)",
    to: "Goldman Sachs Rollover IRA",
    reused: 14,
    total: 18,
    fields: [
      { label: "Household legal name", value: "Priya Shah & Arjun Shah", source: "Passport", reused: true },
      { label: "Legal entity", value: "Shah Family Revocable Trust", source: "Passport", reused: true },
      { label: "Domicile", value: "Los Angeles, CA", source: "Passport", reused: true },
      { label: "Advisor of record", value: "David Park · BrokerCheck 222222", source: "Verification", reused: true },
      { label: "Delivering account", value: "Fidelity 401(k) · •••• 3188", source: "Passport", reused: true },
      { label: "Receiving account", value: "Goldman Rollover IRA · pending", source: "Ops clerk", reused: false },
      { label: "Cost basis method", value: "Average cost (illustrated)", source: "Passport", reused: true },
      { label: "Beneficiaries", value: "Primary: spouse · Contingent: Shah 2016 GST", source: "Passport", reused: true },
      { label: "W-9 / TIN attestation", value: "On file · last4 2291", source: "Reusable docs", reused: true },
      { label: "ACH instructions", value: "J.P. Morgan operating · •••• 4402", source: "Reusable docs", reused: true },
      { label: "Risk questionnaire", value: "Aggressive growth · 2026-06 refresh", source: "Passport", reused: true },
      { label: "Accredited investor letter", value: "Illustrated letter · 2026-03", source: "Reusable docs", reused: true },
      { label: "Passport share consent", value: "On · any paying institution may offer", source: "Consent", reused: true },
      { label: "Morningstar-style holdings extract", value: "Taxable + 401(k) sleeves (fixture)", source: "Illustrated feed", reused: true },
      { label: "Informa-style product mapping", value: "Muni SMA eligibility (fixture)", source: "Illustrated feed", reused: true },
      { label: "Medallion / wet signature", value: "Required at funding", source: "Still needed", reused: false },
      { label: "Plan administrator release", value: "Fidelity recordkeeper queue", source: "Still needed", reused: false },
      { label: "State rollover notice", value: "CA notice to be generated", source: "Still needed", reused: false },
    ],
  },
  verifiedCustodian: {
    badge: "Goldman Sachs",
    accountMask: "Account ending 7720",
    title: "Goldman Private Wealth",
    body: "The taxable joint account is illustrated as custodian-matched to Goldman Sachs. Schwab, Fidelity 401(k), and J.P. Morgan cash remain unverified in this mock so the badge is meaningful.",
  },
};
